version: '3.8'

services:
  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    build: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - data_wordpress:/var/www/html
    networks:
      - net
    restart: always

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - data_mariadb:/var/lib/mysql
    env_file:
      - .env
    networks:
      - net
    restart: always

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build: ./requirements/wordpress
    volumes:
      - data_wordpress:/var/www/html
    env_file:
      - .env
    networks:
      - net
    restart: always

networks:
  net:
    driver: bridge
volumes:
  data_mariadb:
    name: data_mariadb
    driver: local
    driver_opts:
      type: none
      device: /home/fursini/data/mariadb
      o: bind

  data_wordpress:
    name: data_wordpress
    driver: local
    driver_opts:
      type: none
      device: /home/fursini/data/wordpress
      o: bind
